apiVersion: v1
kind: Service
metadata:
  name: pet-store1
  namespace: pet-business
spec:
  selector:
    app: pet-store1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
